version: '3'

services:
  app:
    build:
      context: code
    container_name: app
    entrypoint: dockerize -wait tcp://database:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "npm install && node index.js"
    restart: always
    expose: 
      - 3333
    networks: 
      - node-network
    volumes: 
      - ./code:/usr/src/app
    tty: true
    depends_on: 
      - database

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx: 
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - app

networks: 
  node-network: 
    name: 'node-network'
    driver: 'bridge'